'use client';

/**
 * End-user BYO Web OAuth upload UI (phase 7b).
 * Generated by @egdesk/next-api-plugin — customize styling in your app; do not post JSON through your server.
 */

import { useCallback, useState } from 'react';
import {
  forgetVisitorGcp,
  getStoredVisitorGcpHandle,
  registerVisitorGcp,
  resolveEgdeskPublicUrl,
  setStoredVisitorGcpHandle,
  startVisitorGoogleLogin,
} from '@/egdesk-visitor-google';

export function VisitorGcpByoPanel() {
  const [handle, setHandle] = useState(() => getStoredVisitorGcpHandle() || '');
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  const onUpload = useCallback(async (file: File) => {
    setBusy(true);
    setMessage(null);
    try {
      const text = await file.text();
      const json = JSON.parse(text);
      const result = await registerVisitorGcp({
        oauthClientJson: json,
        handle: handle.trim() || undefined,
        egdeskPublicUrl: resolveEgdeskPublicUrl(),
      });
      const nextHandle = result.handle as string;
      setHandle(nextHandle);
      setStoredVisitorGcpHandle(nextHandle);
      setMessage(
        `Registered ${result.clientIdMasked}. Redirect URI: ${result.redirectUriToRegister}`,
      );
    } catch (err) {
      setMessage(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }, [handle]);

  const onSignIn = useCallback(async () => {
    const h = handle.trim() || getStoredVisitorGcpHandle();
    if (!h) {
      setMessage('Register a Web client JSON first.');
      return;
    }
    await startVisitorGoogleLogin({ gcp: 'self', handle: h });
  }, [handle]);

  const onForget = useCallback(async () => {
    const h = handle.trim();
    if (!h) return;
    setBusy(true);
    try {
      await forgetVisitorGcp(h);
      setStoredVisitorGcpHandle(null);
      setHandle('');
      setMessage('Forgot GCP profile on this site.');
    } catch (err) {
      setMessage(err instanceof Error ? err.message : String(err));
    } finally {
      setBusy(false);
    }
  }, [handle]);

  return (
    <section style={{ maxWidth: 480, margin: '1rem 0', fontFamily: 'system-ui, sans-serif' }}>
      <h2 style={{ fontSize: '1.1rem' }}>Bring your own Google Cloud project</h2>
      <p style={{ fontSize: '0.9rem', color: '#444' }}>
        Upload a Web application OAuth client JSON. Secrets stay on the operator&apos;s EGDesk PC, not this site&apos;s server.
      </p>
      <label style={{ display: 'block', marginBottom: 8 }}>
        Handle (optional)
        <input
          value={handle}
          onChange={(e) => setHandle(e.target.value)}
          placeholder="auto-generated if empty"
          style={{ display: 'block', width: '100%', marginTop: 4 }}
        />
      </label>
      <input
        type="file"
        accept=".json,application/json"
        disabled={busy}
        onChange={(e) => {
          const f = e.target.files?.[0];
          if (f) void onUpload(f);
        }}
      />
      <div style={{ display: 'flex', gap: 8, marginTop: 12 }}>
        <button type="button" disabled={busy} onClick={() => void onSignIn()}>
          Sign in with my GCP
        </button>
        <button type="button" disabled={busy || !handle.trim()} onClick={() => void onForget()}>
          Forget my GCP
        </button>
      </div>
      {message && <p style={{ fontSize: '0.85rem', marginTop: 12 }}>{message}</p>}
    </section>
  );
}
