/** @type {import('next').NextConfig} */
// Generated by EGDesk for production hosting — do not edit.
const nextConfig = {
  basePath: '/t/mcp-server-fxkud1/p/SheetBot',
  assetPrefix: '/t/mcp-server-fxkud1/p/SheetBot',
};
module.exports = nextConfig;
