'use client';

/**
 * Visitor Google OAuth callback.
 * Generated by @egdesk/next-api-plugin — do not edit.
 *
 * Customize login UI in your own pages (e.g. app/login/page.tsx).
 * Set default scopes in egdesk.visitor-auth.ts, or pass them to
 * startVisitorGoogleLogin({ scopes: VISITOR_BASIC_SCOPES }).
 *
 * EGDesk completes Google/Supabase OAuth, then redirects here with ?code=
 * (a one-time EGDesk code, not a Supabase token). This page exchanges it
 * for an opaque visitor session id.
 */

import { useEffect, useState } from 'react';
import { exchangeVisitorAuthCode, resolveVisitorAppPath } from '@/egdesk-visitor-google';

export default function VisitorAuthCallbackPage() {
  const [message, setMessage] = useState('Finishing sign-in…');

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const code = params.get('code');
    const next = params.get('next') || '/';
    if (!code) {
      setMessage('Missing login code. Close this page and try Sign in with Google again.');
      return;
    }
    void exchangeVisitorAuthCode(code)
      .then(async (result: any) => {
        // 서버 DB에 최신 방문자 세션 ID 및 계정 자동 동기화
        try {
          const { getVisitorGoogleStatus } = await import('@/egdesk-visitor-google');
          const status = await getVisitorGoogleStatus();
          const email = status?.email || '';
          const sessionId = result?.sessionId || '';

          if (email && sessionId) {
            await fetch('/api/auth/google/session', {
              method: 'POST',
              headers: { 'Content-Type': 'application/json' },
              body: JSON.stringify({
                email,
                name: email.split('@')[0],
                visitorSessionId: sessionId,
              }),
            }).catch(() => {});
          }
        } catch {}

        const dest = resolveVisitorAppPath(next.startsWith('/') ? next : '/');
        window.location.replace(dest);
      })
      .catch((err: unknown) => {
        const text = err instanceof Error ? err.message : String(err);
        setMessage('Sign-in failed: ' + text);
      });
  }, []);

  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: 24 }}>
      <p>{message}</p>
    </main>
  );
}
