'use client';

/**
 * Visitor Google OAuth callback.
 * Generated by @egdesk/next-api-plugin.
 *
 * EGDesk completes Google/Supabase OAuth, then redirects here with ?code=
 * (a one-time EGDesk code, not a Supabase token). This page exchanges it
 * for an opaque visitor session id.
 */

import { useEffect, useState } from 'react';
import { exchangeVisitorAuthCode, getVisitorGoogleStatus, resolveVisitorAppPath } from '@/egdesk-visitor-google';

export default function VisitorAuthCallbackPage() {
  const [message, setMessage] = useState('Finishing sign-in…');

  useEffect(() => {
    const params = new URLSearchParams(window.location.search);
    const code = params.get('code');
    const next = params.get('next') || '/';
    if (!code) {
      setMessage('Missing login code. Close this page and try Sign in with Google again.');
      return;
    }
    void exchangeVisitorAuthCode(code)
      .then(async (result) => {
        setMessage('세션을 구성하는 중입니다…');

        // 1. 방문자 이메일 및 프로필 정보 확인
        let email = (result as any)?.email || (result as any)?.user?.email;
        let name = (result as any)?.name || (result as any)?.user?.user_metadata?.full_name;
        let image = (result as any)?.image || (result as any)?.user?.user_metadata?.avatar_url;

        if (!email) {
          const status = await getVisitorGoogleStatus().catch(() => null);
          if (status?.connected && status?.email) {
            email = status.email;
          }
        }

        // 2. NextAuth 세션 쿠키 발급 및 회원 동기화 (/api/auth/google/session)
        if (email) {
          await fetch('/api/auth/google/session', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ email, name, image }),
          }).catch((err) => {
            console.warn('NextAuth session sync warning:', err);
          });
        }

        const dest = resolveVisitorAppPath(next.startsWith('/') ? next : '/');
        window.location.replace(dest);
      })
      .catch((err: unknown) => {
        const text = err instanceof Error ? err.message : String(err);
        setMessage('Sign-in failed: ' + text);
      });
  }, []);

  return (
    <main style={{ fontFamily: 'system-ui, sans-serif', padding: 24 }}>
      <p>{message}</p>
    </main>
  );
}
