import { NextRequest, NextResponse } from 'next/server';

/**
 * Proxies operator/end-user direct OAuth callbacks to desktop MCP.
 * Generated by @egdesk/next-api-plugin — do not edit.
 */
function resolveEgdeskMcpInternalUrl(): string {
  const internal = process.env.EGDESK_MCP_INTERNAL_URL;
  if (internal && internal.trim()) return internal.replace(/\/$/, '');
  return 'http://localhost:8080';
}

export async function GET(request: NextRequest) {
  const internal = resolveEgdeskMcpInternalUrl();
  const incoming = new URL(request.url);
  const target = new URL(`${internal}/visitor-auth/callback`);
  target.search = incoming.search;
  const origin = request.headers.get('origin') || incoming.origin;
  const response = await fetch(target.toString(), {
    method: 'GET',
    redirect: 'manual',
    headers: {
      Origin: origin,
      'X-Visitor-Origin': origin,
    },
    cache: 'no-store',
  });
  const location = response.headers.get('location');
  if (response.status >= 300 && response.status < 400 && location) {
    return NextResponse.redirect(location, response.status);
  }
  const text = await response.text();
  return new NextResponse(text, {
    status: response.status,
    headers: { 'Content-Type': response.headers.get('content-type') || 'text/html; charset=utf-8' },
  });
}
